#!/bin/bash
# ================================================================
# agent-view-quota-warn.sh — Warn on parallel Task spawn quota burn
# ================================================================
# PURPOSE:
#   Claude Code Agent View (v2.1.139+) lets operators run multiple
#   Task / sub-agent sessions in parallel via /bg or Background
#   Sessions. Each parallel agent burns quota at the full rate —
#   ten parallel agents burn quota approximately ten times faster
#   than a single interactive session. Plus, each session's one-line
#   summary is generated by Haiku and billed as a normal API call.
#
#   This hook detects when an operator is about to spawn an Nth
#   concurrent Task and emits a warning so they can decide whether
#   to throttle. The warning includes the count of currently-tracked
#   concurrent Tasks in the session.
#
# TRIGGER: PreToolUse
# MATCHER: "Task"
#
# HOW IT WORKS:
#   - Tracks concurrent Task invocations per session via a counter
#     keyed on CLAUDE_CODE_SESSION_ID (falls back to PPID).
#   - On Task spawn, increments counter and checks against threshold.
#   - On Task completion (PostToolUse Task), decrement counter.
#     (Use the companion hook below for the decrement side.)
#   - Emits a warning to stderr if counter exceeds threshold.
#   - Does NOT block (exit 0). Warning is advisory.
#
# CONFIGURATION:
#   CC_AGENT_VIEW_WARN_THRESHOLD  (default 3) — warn when this many
#                                  concurrent Tasks are tracked.
#   CC_AGENT_VIEW_PEAK_THRESHOLD  (default 10) — louder warning above
#                                  this count.
#   CC_AGENT_VIEW_QUIET           (default unset) — suppress all
#                                  warnings if set to "1".
#
# RELATED:
#   - Issue #58570 (Agent View not enabled for Claude API users)
#   - Hatena article on four Agent View pitfalls (2026-05-16):
#     https://yurukusa-dev.hatenablog.com/entry/2026/05/16/104555
# ================================================================

set -uo pipefail

INPUT=$(cat)
TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name // empty' 2>/dev/null || echo "")

# Only act on Task tool spawns
[ "$TOOL_NAME" = "Task" ] || exit 0

# Suppression via env
[ "${CC_AGENT_VIEW_QUIET:-0}" = "1" ] && exit 0

THRESHOLD="${CC_AGENT_VIEW_WARN_THRESHOLD:-3}"
PEAK="${CC_AGENT_VIEW_PEAK_THRESHOLD:-10}"

# Identify session — prefer CLAUDE_CODE_SESSION_ID, fall back to PPID
SESSION_KEY="${CLAUDE_CODE_SESSION_ID:-ppid-${PPID:-unknown}}"
COUNTER_FILE="/tmp/cc-agent-view-tasks-${SESSION_KEY}"

# Initialize if absent
[ -f "$COUNTER_FILE" ] || echo "0" > "$COUNTER_FILE"

# Read, increment, write
COUNT=$(cat "$COUNTER_FILE" 2>/dev/null || echo "0")
# Numeric guard
case "$COUNT" in
    ''|*[!0-9]*) COUNT=0 ;;
esac
COUNT=$((COUNT + 1))
echo "$COUNT" > "$COUNTER_FILE"

# Emit warning if threshold exceeded
if [ "$COUNT" -ge "$PEAK" ]; then
    cat >&2 <<EOF
[agent-view-quota-warn] PEAK: ${COUNT} concurrent Tasks tracked in this session.
  Each parallel Task burns quota at the full rate. At ${COUNT}x parallelism your
  monthly credit allowance can be exhausted in 1/${COUNT}th of the usual time.
  Plus, Agent View's per-session Haiku summary calls accumulate as billable
  API calls (USD 1/MTok input on Haiku 4.5).
  Set CC_AGENT_VIEW_QUIET=1 to suppress this warning.
EOF
elif [ "$COUNT" -ge "$THRESHOLD" ]; then
    cat >&2 <<EOF
[agent-view-quota-warn] ${COUNT} concurrent Tasks tracked. Parallel agent execution
  multiplies quota burn linearly. Six days before the 2026-06-15 credit cliff,
  the cost of parallel agents increases sharply — Pro USD 20, Max 5x USD 100,
  Max 20x USD 200 monthly programmatic credit, then API rates above.
  Set CC_AGENT_VIEW_QUIET=1 to suppress.
EOF
fi

exit 0
