#!/bin/bash
# opus48-thinking-wedge-advisor.sh — Warn when a mid-conversation model swap
#                                   from Opus 4.7 to Opus 4.8 is about to hit
#                                   the Cluster 13 Axis G hard 400.
#
# Solves: Cluster 13 Axis G — Opus 4.7 → Opus 4.8 mid-conversation model swap
#         produces a hard 400 ("thinking blocks must remain as original
#         response") that strip-on-retry does not recover from. The signature
#         of a thinking block generated by 4.7 is computed against the 4.7
#         reasoning state; 4.8's resume path applies a stricter validation
#         that rejects the 4.7-signed block even when the text is preserved
#         verbatim. Unlike Cluster 13A (signature/text mismatch, soft 400),
#         13G is structural: the only known full fix is staying on 4.7.
#
# Issues addressed: #63607 (Opus 4.8 incompatibility, "must remain as
#         original response" phrasing), #63606, #63612, #63412 (Opus 4.8
#         on long tool-heavy chats; 4.7 unaffected). Field guide on the
#         seven-pattern split: https://github.com/anthropics/claude-code/issues/63147#issuecomment-4580358273
#
# How it works: Notification hook. Reads the model name from the event body
#   (falling back to $CLAUDE_MODEL). Compares to the model recorded on the
#   previous Notification. When the transition matches "Opus 4.7 → Opus 4.8"
#   AND the current session transcript carries the empty-text + signed
#   thinking block shape (the precondition for the 4.8 strict validation to
#   trip), emits a stderr advisory naming sub-pattern 13G, the four central
#   issues, and the only known full-fix path (stay on 4.7 + 2.1.152).
#
#   The hook NEVER blocks — exit 0 always. The advisory is calibrated to a
#   transition shape that the operator can act on before the next API call.
#
# Differentiation from model-version-change-alert.sh:
#   The general alert fires on any model change. This hook fires only on the
#   13G transition shape (4.7 → 4.8 + signed thinking blocks in transcript)
#   and articulates the specific failure mode and workaround. The two hooks
#   are complementary; running both gives general visibility plus 13G-specific
#   guidance.
#
# Environment variables:
#   CC_CLUSTER_13G_DISABLE=1         — disable advisory entirely
#   CC_CLUSTER_13G_VERBOSE=1         — include sample signature lengths
#   CC_CLUSTER_13G_TRANSCRIPT        — override transcript path (test)
#   CC_CLUSTER_13G_HISTORY_FILE      — override model history file (test)
#   CC_CLUSTER_13G_FORCE=1           — fire regardless of source (test)
#
# TRIGGER: Notification
# MATCHER: "" (filters event internally)

set -uo pipefail

INPUT=$(cat)
[ "${CC_CLUSTER_13G_DISABLE:-0}" = "1" ] && exit 0

# Resolve current model from event body or environment.
BODY_MODEL=$(printf '%s' "$INPUT" | jq -r '.model // empty' 2>/dev/null)
CURRENT_MODEL="${BODY_MODEL:-${CLAUDE_MODEL:-}}"
[ -z "$CURRENT_MODEL" ] && exit 0

# History file persists the last observed model across hook invocations.
HISTORY_FILE="${CC_CLUSTER_13G_HISTORY_FILE:-/tmp/cc-cluster-13g-model-history}"
PREV_MODEL=$(cat "$HISTORY_FILE" 2>/dev/null || true)

# Always record current model on exit (fail-open if we cannot write).
record_current_model() {
    printf '%s' "$CURRENT_MODEL" > "$HISTORY_FILE" 2>/dev/null || true
}
trap record_current_model EXIT

# Require a previous observation to detect a transition.
[ -z "$PREV_MODEL" ] && exit 0

# Same model — no transition.
[ "$PREV_MODEL" = "$CURRENT_MODEL" ] && exit 0

# Identify the 13G transition: Opus 4.7 series → Opus 4.8 series.
# Accept any string containing "opus-4-7" / "opus-4-8" (case-insensitive)
# to match both API model IDs and Claude Code's internal naming.
is_opus_47() {
    printf '%s' "$1" | grep -qiE 'opus[-_. ]*4[-_. ]*7'
}
is_opus_48() {
    printf '%s' "$1" | grep -qiE 'opus[-_. ]*4[-_. ]*8'
}

if [ "${CC_CLUSTER_13G_FORCE:-0}" != "1" ]; then
    is_opus_47 "$PREV_MODEL" || exit 0
    is_opus_48 "$CURRENT_MODEL" || exit 0
fi

# Precondition for 13G to fire on the next API call: the transcript carries
# signed thinking blocks emitted by the prior model. If there are no signed
# thinking blocks, the swap may complete cleanly and the advisory is noise.
LATEST="${CC_CLUSTER_13G_TRANSCRIPT:-}"
if [ -z "$LATEST" ]; then
    PROJ_DIR="${CC_PROJECT_DIR:-$PWD}"
    SLUG=$(printf '%s' "$PROJ_DIR" | sed 's|^/||; s|/|-|g')
    TRANSCRIPT_DIR="${HOME}/.claude/projects/${SLUG}"
    [ -d "$TRANSCRIPT_DIR" ] || exit 0
    LATEST=$(ls -t "$TRANSCRIPT_DIR"/*.jsonl 2>/dev/null | head -1)
fi
[ -n "$LATEST" ] || exit 0
[ -r "$LATEST" ] || exit 0

# Scan for any signed thinking block (text empty or non-empty — the 13G
# trigger is the 4.7-computed signature itself, independent of whether the
# text was emptied to "" as in 13A).
SCAN=$(jq -rR 'fromjson? | select(.type == "assistant") | .message.content[]? | select(.type == "thinking" and ((.signature // "") | length) > 0) | (.signature | length)' "$LATEST" 2>/dev/null || true)
[ -z "$SCAN" ] && exit 0

COUNT=$(printf '%s\n' "$SCAN" | grep -c .)
SIG_SAMPLE=$(printf '%s' "$SCAN" | head -3 | tr '\n' ' ')

{
    echo "[opus48-thinking-wedge-advisor] Cluster 13G transition detected."
    echo ""
    echo "  Previous model: $PREV_MODEL"
    echo "  Current model:  $CURRENT_MODEL"
    echo "  Transcript:     $LATEST"
    echo "  Signed thinking block(s) carried from prior model: ${COUNT}"
    echo ""
    echo "The next API call may hit the hard 400:"
    echo "    \`thinking\` or \`redacted_thinking\` blocks in the latest assistant"
    echo "    message must remain as they were in the original response."
    echo ""
    echo "This 400 differs from the Cluster 13A wedge: strip-on-retry does NOT"
    echo "recover, because the 4.7-computed signature is structurally rejected"
    echo "by the 4.8 validation path. The session cannot continue on 4.8 once"
    echo "this fires."
    echo ""
    echo "Recommended actions:"
    echo "  - Switch back to Opus 4.7 with /model and continue on this session."
    echo "  - For 4.8 work, start a fresh session without prior 4.7-signed blocks."
    echo "  - Pinning Claude Code to 2.1.152 avoids the related Cluster 13F"
    echo "    context-ops failure that 13G frequently compounds with."
    echo ""
    echo "Reference: https://github.com/anthropics/claude-code/issues/63607"
    echo "Related: https://github.com/anthropics/claude-code/issues/63147#issuecomment-4580358273"
    if [ "${CC_CLUSTER_13G_VERBOSE:-0}" = "1" ]; then
        echo ""
        echo "(first 3 signature lengths: ${SIG_SAMPLE})"
    fi
} >&2

exit 0
